jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chan
    url: jdbc:mysql://localhost:3306/WhatEverApp?serverTimezone=UTC&characterEncoding=UTF-8
    password: chan1234
  data:
    mongodb:
      #username: chan
      #password:1234
      spring:
        data:
          mongodb:
            host: localhost
            port: 27017
            database: WhatEverApp
  jpa:
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.format_sql: true

