jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rdstutorial.copner1jrptp.ap-northeast-2.rds.amazonaws.com:3306/WhatEverApp?useSSL=false&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: chan
    password: chan1234

    hikari:
      max-lifetime: 177000

#    url: jdbc:mysql://localhost:3306/WhatEverApp?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&characterEncoding=UTF-8
#    username: chan
#    password: chan1234

  data:
    mongodb:
      uri: mongodb://chan:chan1234@ec2-52-78-201-175.ap-northeast-2.compute.amazonaws.com/test?authSource=admin

  servlet:
    multipart:
      max-file-size: 1MB
  jpa:
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.format_sql: true

server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024


file: C:\Users\82104\userImage\

fcm:
  key:
    path: gjgs-fcm.json
    scope: https://www.googleapis.com/auth/cloud-platform